### PR TITLE
Fix #221 by bumping Go.

### LINKED ISSUE #221: Launchd worker fails with "no route to host" on Sequoia
We have been running Orchard workers, configured using launchd on Sonoma for a long time already. The implementation was based on the documentation here: https://tart.run/orchard/deploying-workers/#launchd

However, after upgrading one of our hosts to Sequoia, the workers that is started via launchd no longer connects to the controller.

```
{"level":"warn","ts":1732044922.827034,"msg":"failed to register worker: API client failed to make a request: Post \"https://<redacted>:6120/v1/workers\": dial tcp <redacted>:6120: connect: no route to host"}
```

We suspect it is related to new privacy settings in Sequoia related to local network access. The dialog to allow local network access does not appear.

Not sure if this is related, but bumping Go might resolve the issue:
https://github.com/golang/go/issues/68678
Any interest in a pull-request that bumps Go to test this?

It might also be related to this one:
https://github.com/cirruslabs/tart/issues/921

### PR DESCRIPTION
**Pull request by timpeeters**
Fixes #221

### CODE REVIEW

**Comment by edigaryev** [comment]
Hi Tim 👋 

We'd probably need to bump the Golang version used to build the Orchard instead, see https://github.com/cirruslabs/orchard/pull/222.

I'm happy to merge this if you cherry-pick the changes from that PR.

**Comment by edigaryev** [comment]
It's weird, but I'm still not seeing the LC_UUID in the binary produced by Golang 1.23.3.

You can check this yourself by downloading the `binaries` artifact [here](https://cirrus-ci.com/task/5727017235120128) and running `dwarfdump -u dist/orchard_darwin_arm64_v8.0/orchard`.

**Comment by timpeeters** [comment]
Hmm strange, I'll have a look here as well.
Nevertheless, I've successfully tested a locally built binary using Golang 1.23.3 and it did no longer result in the "no route to host" error.

**Comment by edigaryev** [comment]
>It's weird, but I'm still not seeing the LC_UUID in the binary produced by Golang 1.23.3.

Oh, I now see [why](https://github.com/golang/go/issues/68678#issuecomment-2447965386):

> Just give an update: This is fixed on tip (to be released in Go 1.24), by generating LC_UUID by default.
> 
> For previous releases (Go 1.22 and 1.23), we did a simpler backport, which requires a Go linker flag (`-B gobuildid`) to generate the UUID. Compared to `-linkmode=external`, this does not require a C toolchain installation (and therefore easier to work with in a cross compilation setting). This will be included in the next Go 1.22 and 1.23 minor releases (early November).

@timpeeters we'll probably need to update the `.goreleaser.yml` as follows:

```patch
diff --git a/.goreleaser.yml b/.goreleaser.yml
index ad5a8ea..b53d35c 100644
--- a/.goreleaser.yml
+++ b/.goreleaser.yml
@@ -10,6 +10,7 @@ builds:
     ldflags: >
       -X github.com/cirruslabs/orchard/internal/version.Version={{.Version}}
       -X github.com/cirruslabs/orchard/internal/version.Commit={{.ShortCommit}}
+      -B gobuildid
     env:
       - CGO_ENABLED=0
     goos:
```

**Comment by timpeeters** [comment]
Ok, I've just added the flag. Waiting for the build now.

**Review by edigaryev — APPROVED** [review]

**Comment by hblockx** [comment]
but isn't that only solving the "issue" by addressing the permission at the end of binary-calling? The same issue is appearing when trying to build images with tart, as actually the tart-binary is the one which needs the permission, as it is using a bridge-network to access a vm and this now seems to trigger the local-networking permission?
In gitlab there is an open issue regarding that topic:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/38262

**Comment by edigaryev** [comment]
>tart-binary is the one which needs the permission, as it is using a bridge-network to access a vm

Tart does not access its own VMs in any way over the network. So it doesn't need the "Local Network" permission to operate correctly.

The only exception to this is when doing `clone`/`pull` against OCI registries hosted on private IPv4 ranges. But in this case, you can simply approve the permission in the UI.

**Comment by hblockx** [comment]
In case of gitLab-Runner and packer-builds, which binary actually should deal with the local-networking permission? It also kinda feels wrong that the gitlab runner is asking for it, although it is packer / tart accessing a vm? I thought tart accesses the VM via using the SSH command and the need of the permission can be provided top-down, so the top-level-caller may provide it for calling binaries which actually need the permission...

**Comment by edigaryev** [comment]
>It also kinda feels wrong that the gitlab runner is asking for it, although it is packer / tart accessing a vm?

Here's a quote from [TN3179: Understanding local network privacy (macOS considerations)](https://developer.apple.com/documentation/technotes/tn3179-understanding-local-network-privacy#macOS-considerations):

>When a process performs a local network operation, macOS tries to track down the responsible code. For example, if your app spawns a helper tool and the helper tool performs a local network operation, macOS considers the app to be the responsible code.

**Pull request merged**
